# Config file used for internal tools at Auctionet

docker_services:
  postgres:
    image: "postgres:14.4-alpine" # keep in sync with .circleci/config.yml
    version: "14.4"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/ex_gridhook/postgres:/var/lib/postgresql/data"
