# Config file used for internal tools at Auctionet

dependencies:
  node:
    version: "15.6.0"
    checksum: "1dd3681e85bb9c8205a331bfac5121050893defb5ad9d04698239aeef4e736b3"

docker_services:
  postgres:
    image: "postgres:13.2" # keep in sync with .circleci/config.yml
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/ex_gridhook/postgres:/var/lib/postgresql/data"
