# Config file used for internal tools at Auctionet

docker_services:
  postgres:
    image: "postgres:18.1-alpine"
    version: "18.1"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/ex_gridhook/postgres:/var/lib/postgresql"
