# Config file used for internal tools at Auctionet

dependencies:
  node: "8.10.0"

docker_services:
  postgres:
    image: "postgres:9.6.16"
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/ex_gridhook/postgres:/var/lib/postgresql/data"
