# Config file used for internal tools at Auctionet

dependencies:
  node:
    version: "16.11.1"
    checksum: "8b5a54b284e524984772d34dc2efc68a10fc2f91db11390c6035ef2a9509ef2c"

docker_services:
  postgres:
    image: "postgres:13.4" # keep in sync with .circleci/config.yml
    options: "-e POSTGRES_PASSWORD=dev --publish 5432 -v $DATABASE_ROOT/ex_gridhook/postgres:/var/lib/postgresql/data"
