version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0 # https://circleci.com/developer/orbs/orb/circleci/heroku

jobs:
  test:
    resource_class: medium
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Installing tools"
          command: sudo apt-get update -q && sudo apt-get install -q -y ruby && sudo apt-get install -q -y bash  && sudo apt-get install -q -y make
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          name: "Checking out code"
      - run:
          name: "Build test image"
          command: script/ci/pipeline.sh build_test "make test-image"
      - run:
          name: "Run linters and code analysis"
          command: script/ci/pipeline.sh lint "script/ci/docker/lint.sh"
      - run:
          name: "Run tests"
          command: script/ci/pipeline.sh test "script/ci/docker/test.sh"

  prepare_app_image:
    environment:
      APP_NAMES: |
          auctionet-ex-gridhook
    resource_class: medium
    docker:
      - image: cimg/base:stable
    steps:
      - heroku/install
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: false
      - run:
          name: "Preparing app image"
          command: |
            script/ci/pipeline.sh prepare_image "script/ci/prepare_app_image.sh"

  deploy_to_production:
    docker:
      - image: cimg/base:stable
    steps:
      - heroku/install
      - checkout
      - run:
          name: "Release production"
          command: script/ci/pipeline.sh deploy "script/ci/deploy.sh auctionet-ex-gridhook"

workflows:
  deploy-workflow:
    jobs:
      - test:
          context: shared-config
      - prepare_app_image:
          context: shared-config
          filters:
            branches:
              only:
                - master
      - deploy_to_production:
          context: shared-config
          requires:
            - test
            - prepare_app_image
          filters:
            branches:
              only:
                - master
