version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5.2
      - image: postgres:9.6.1
        env:
          - POSTGRES_USER=ubuntu
        working_directory: ~/ex_exgridhook
        steps:
          - type: checkout
          - run: mix local.rebar --force
          - run: mix local.hex --force
          - run: mix deps.get
          - run: mix test
