version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0 # https://circleci.com/developer/orbs/orb/circleci/heroku

  deploy_to_production:
    docker:
      - image: cimg/base:stable
    steps:
      - heroku/install
      - checkout
      - run:
          name: "Release production"

workflows:
  deploy-workflow:
    jobs:
      - test:
          context: shared-config
      - prepare_app_image:
          context: shared-config
      - deploy_to_production:
          context: shared-config
          requires:
            - test
            - prepare_app_image
          filters:
            branches:
              only:
                - master
