version: 2
jobs:
  test:
    docker:
      - image: cimg/elixir:1.13.4 # Keep in sync with the version in elixir_buildpack.config
      - image: postgres:13.4 # Keep in sync with dev.yml
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_HOST_AUTH_METHOD=trust # trust = allow all https://www.postgresql.org/docs/current/auth-trust.html

    steps:
      - checkout:
          name: "Checking out code"
      - run:
          name: "Setting up package manager"
          command: mix local.rebar --force && mix local.hex --force
      - run:
          name: "Getting deps"
          command: mix deps.get
      - run:
          name: "Compiling code"
          command: MIX_ENV=test mix compile
      - run:
          name: "Running tests"
          command: script/ci/pipeline.sh tests "script/ci/tests.sh"

  deploy:
    docker:
      - image: cimg/ruby:3.1 # Latest available Ruby; only used for build scripts

    steps:
      - checkout:
          name: "Checking out code"
      - run:
          name: "Deploying to production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              script/ci/pipeline.sh deploy_production "script/ci/deploy.sh $HEROKU_APP_NAME"
            fi

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          context: pipeline-and-heroku
      - deploy:
          context: pipeline-and-heroku
          requires:
            - test
          filters:
            branches:
              only: master
