import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :ex_gridhook, ExGridhookWeb.Endpoint,
  http: [port: System.get_env("PORT") || 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "41LmIyIK6V9rRQXw6ycjPDTik1jkJy/lIBLPg9Xn1hgRnDNCAQ53zyoeCnH4Sk1i",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ex_gridhook, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ex_gridhook, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ex_gridhook, ExGridhookWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ex_gridhook_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

  # Enable dev routes for dashboard and mailbox
config :ex_gridhook, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# # Disable swoosh api client as it is only required for production adapters.
# config :swoosh, :api_client, false

# Configure your database
if System.get_env("DEVBOX") do
  config :ex_gridhook, ExGridhook.Repo,
    adapter: Ecto.Adapters.Postgres,
    username: "postgres",
    password: "dev",
    database: "ex_gridhook_dev",
    hostname: "localhost",
    port: System.cmd("service_port", ["postgres"]) |> elem(0) |> String.trim(),
    pool_size: 10
else
  config :ex_gridhook, ExGridhook.Repo,
    adapter: Ecto.Adapters.Postgres,
    username: System.get_env("DB_USER") || System.get_env("USER"),
    password: "",
    database: "ex_gridhook_dev",
    hostname: "localhost",
    pool_size: 10
end
